### PR TITLE
Updating script, going to test it on the apo kinase, just to get this…

### PR DESCRIPTION
**Pull request by steven-albanese**
… moving

### CODE REVIEW

**Comment by jchodera** [comment]
For some reason, the SAMS repo is now so big I can't check it out from the airport. Did you end up checking anything large in?

**Comment by jchodera** [comment]
Or checking something big in and then deleting it?  The git history may have some large files in it and still slow things down, even if they have been deleted afterwards.

**Comment by jchodera** [comment]
If we ended up with large files in there, we will need to **very carefully** expunge them from the git history:
https://help.github.com/articles/removing-files-from-a-repository-s-history/

This is **extremely dangerous**.

**Comment by steven-albanese** [comment]
I don't think I checked anything in too big, let me look

**Comment by steven-albanese** [comment]
Ah I see what it is, it's `output.pdb`, it's huge. What's the best protocol to remove it? Move it out of the repo and then clean it from the git history?

**Pull request merged**
